In [1]:
import pandas as pd
import pandera as pa

In [2]:
valores_ausentes = ['**','###!', '####', '****', '*****', 'NULL', " "]
df = pd.read_csv('ocorrencia_2010_2020.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True, na_values = valores_ausentes)
df.head(10)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,N�O
1,40349,INCIDENTE,BEL�M,PA,SBBE,2010-01-03,11:05:00,0,N�O
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,N�O
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,N�O
4,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,N�O
5,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0,N�O
6,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0,SIM
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
8,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2,N�O
9,39711,INCIDENTE GRAVE,PAR� DE MINAS,MG,NaN,2010-01-10,20:00:00,0,N�O

In [3]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes": pa.Column(pa.Int)
    })

In [4]:
schema.validate(df)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,N�O
1,40349,INCIDENTE,BEL�M,PA,SBBE,2010-01-03,11:05:00,0,N�O
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,N�O
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,N�O
4,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5746,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,N�O
5747,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,NaN,2020-12-30,18:30:00,0,N�O
5748,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,N�O
5749,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0,N�O
5750,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,N�O

In [5]:
df.dtypes

codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_saida_pista              object
dtype: object

In [6]:
df.loc[1]

codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BEL�M
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
ocorrencia_saida_pista                      N�O
Name: 1, dtype: object

In [7]:
df.iloc[1]

codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BEL�M
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
ocorrencia_saida_pista                      N�O
Name: 1, dtype: object

In [8]:
df.iloc[-1]

codigo_ocorrencia2                        79844
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                RIO DE JANEIRO
ocorrencia_uf                                RJ
ocorrencia_aerodromo                       SBJR
ocorrencia_dia              2020-12-31 00:00:00
ocorrencia_hora                        13:24:00
total_recomendacoes                           0
ocorrencia_saida_pista                      N�O
Name: 5750, dtype: object

In [9]:
df.tail()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
5746,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,N�O
5747,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,NaN,2020-12-30,18:30:00,0,N�O
5748,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,N�O
5749,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0,N�O
5750,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,N�O

In [10]:
df.iloc[12:42]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
12,40414,INCIDENTE,BRAS�LIA,DF,SBBR,2010-01-10,03:00:00,0,N�O
13,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2,N�O
14,40107,ACIDENTE,GURUP�,PA,SNGU,2010-01-12,14:30:00,0,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
16,39809,INCIDENTE,S�O PAULO,SP,NaN,2010-01-15,15:00:00,0,N�O
17,39810,INCIDENTE,SALVADOR,BA,NaN,2010-01-15,18:23:00,0,N�O
18,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0,N�O
19,44575,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-17,12:27:00,0,N�O
20,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0,N�O
21,39320,ACIDENTE,FAROL,PR,NaN,2010-01-19,18:30:00,4,N�O
22,39851,INCIDENTE,PASSO FUNDO,RS,SBPF,2010-01-19,03:00:00,0,N�O
23,40311,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,13:20:00,0,N�O
24,41577,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,12:16:00,0,N�O
25,39772,INCIDENTE,UBERL�NDIA,MG,NaN,2010-01-20,18:58:00,0,N�O
26,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0,N�O
27,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0,N�O
28,39321,ACIDENTE,PONTES E LACERDA,MT,NaN,2010-01-23,13:00:00,2,N�O
29,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2,SIM
30,39849,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-23,03:30:00,0,N�O
31,39323,ACIDENTE,CASIMIRO DE ABREU,RJ,NaN,2010-01-24,16:15:00,0,N�O
32,39318,ACIDENTE,SENADOR JOS� PORF�RIO,PA,NaN,2010-01-25,16:20:00,5,N�O
33,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0,N�O
34,39322,ACIDENTE,S�O BERNARDO DO CAMPO,SP,NaN,2010-01-26,13:50:00,2,N�O
35,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0,N�O
36,39850,INCIDENTE,BEL�M,PA,SBJC,2010-01-26,14:30:00,0,N�O
37,39319,ACIDENTE,IPER�,SP,NaN,2010-01-27,11:25:00,3,N�O
38,39627,INCIDENTE,FLORIAN�POLIS,SC,SBFL,2010-01-27,16:15:00,0,N�O
39,40617,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-27,20:06:00,0,N�O
40,39158,INCIDENTE,BEL�M,PA,NaN,2010-01-28,16:00:00,0,N�O
41,39687,INCIDENTE GRAVE,PORTO UNI�O,SC,NaN,2010-01-28,10:30:00,1,N�O

In [11]:
df.loc[12:42]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
12,40414,INCIDENTE,BRAS�LIA,DF,SBBR,2010-01-10,03:00:00,0,N�O
13,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2,N�O
14,40107,ACIDENTE,GURUP�,PA,SNGU,2010-01-12,14:30:00,0,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
16,39809,INCIDENTE,S�O PAULO,SP,NaN,2010-01-15,15:00:00,0,N�O
17,39810,INCIDENTE,SALVADOR,BA,NaN,2010-01-15,18:23:00,0,N�O
18,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0,N�O
19,44575,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-17,12:27:00,0,N�O
20,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0,N�O
21,39320,ACIDENTE,FAROL,PR,NaN,2010-01-19,18:30:00,4,N�O
22,39851,INCIDENTE,PASSO FUNDO,RS,SBPF,2010-01-19,03:00:00,0,N�O
23,40311,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,13:20:00,0,N�O
24,41577,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,12:16:00,0,N�O
25,39772,INCIDENTE,UBERL�NDIA,MG,NaN,2010-01-20,18:58:00,0,N�O
26,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0,N�O
27,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0,N�O
28,39321,ACIDENTE,PONTES E LACERDA,MT,NaN,2010-01-23,13:00:00,2,N�O
29,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2,SIM
30,39849,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-23,03:30:00,0,N�O
31,39323,ACIDENTE,CASIMIRO DE ABREU,RJ,NaN,2010-01-24,16:15:00,0,N�O
32,39318,ACIDENTE,SENADOR JOS� PORF�RIO,PA,NaN,2010-01-25,16:20:00,5,N�O
33,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0,N�O
34,39322,ACIDENTE,S�O BERNARDO DO CAMPO,SP,NaN,2010-01-26,13:50:00,2,N�O
35,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0,N�O
36,39850,INCIDENTE,BEL�M,PA,SBJC,2010-01-26,14:30:00,0,N�O
37,39319,ACIDENTE,IPER�,SP,NaN,2010-01-27,11:25:00,3,N�O
38,39627,INCIDENTE,FLORIAN�POLIS,SC,SBFL,2010-01-27,16:15:00,0,N�O
39,40617,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-27,20:06:00,0,N�O
40,39158,INCIDENTE,BEL�M,PA,NaN,2010-01-28,16:00:00,0,N�O
41,39687,INCIDENTE GRAVE,PORTO UNI�O,SC,NaN,2010-01-28,10:30:00,1,N�O
42,39747,INCIDENTE,CAIRU,BA,SNCL,2010-01-31,19:47:00,4,N�O

In [12]:
df.loc[:,'ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
5746    SP
5747    TO
5748    RJ
5749    MS
5750    RJ
Name: ocorrencia_uf, Length: 5751, dtype: object

In [13]:
df['ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
5746    SP
5747    TO
5748    RJ
5749    MS
5750    RJ
Name: ocorrencia_uf, Length: 5751, dtype: object

In [14]:
df.isna().sum()

codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  1
ocorrencia_aerodromo        2348
ocorrencia_dia                 0
ocorrencia_hora                0
total_recomendacoes            0
ocorrencia_saida_pista         0
dtype: int64

In [15]:
df.isnull().sum()

codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  1
ocorrencia_aerodromo        2348
ocorrencia_dia                 0
ocorrencia_hora                0
total_recomendacoes            0
ocorrencia_saida_pista         0
dtype: int64

In [16]:
df.ocorrencia_uf.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
5746    False
5747    False
5748    False
5749    False
5750    False
Name: ocorrencia_uf, Length: 5751, dtype: bool

In [17]:
df.loc[df.ocorrencia_uf.isnull()]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
2227,49474,ACIDENTE,�GUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0,N�O

In [18]:
filtro  = df.ocorrencia_uf.isnull()
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
2227,49474,ACIDENTE,�GUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0,N�O

In [19]:
filtro  = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,N�O
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,N�O
5,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0,N�O
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
9,39711,INCIDENTE GRAVE,PAR� DE MINAS,MG,NaN,2010-01-10,20:00:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5740,79754,INCIDENTE GRAVE,NOVA MARING�,MT,NaN,2020-12-28,13:00:00,0,SIM
5743,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0,SIM
5744,79755,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0,N�O
5747,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,NaN,2020-12-30,18:30:00,0,N�O
5749,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0,N�O

In [20]:
df.count()

codigo_ocorrencia2          5751
ocorrencia_classificacao    5751
ocorrencia_cidade           5751
ocorrencia_uf               5750
ocorrencia_aerodromo        3403
ocorrencia_dia              5751
ocorrencia_hora             5751
total_recomendacoes         5751
ocorrencia_saida_pista      5751
dtype: int64

In [21]:
# ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
63,39992,ACIDENTE,S�O PAULO,SP,SBMT,2010-02-17,20:07:00,11,SIM
326,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19,SIM
530,43471,ACIDENTE,S�O PAULO,SP,NaN,2010-12-14,20:15:00,11,N�O
727,44377,ACIDENTE,IT�POLIS,SP,SDIO,2011-04-09,14:50:00,11,N�O
872,44796,ACIDENTE,RECIFE,PE,SBRF,2011-07-13,09:54:00,23,N�O
884,44888,INCIDENTE GRAVE,S�O JOS� DOS PINHAIS,PR,SBCT,2011-07-15,17:05:00,11,N�O
1062,45554,INCIDENTE GRAVE,UBERL�NDIA,MG,SBUL,2011-11-15,02:15:00,20,SIM
1972,47938,INCIDENTE,BRAS�LIA,DF,SBBR,2013-04-13,18:00:00,11,N�O
2795,52265,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13,N�O
3930,66432,INCIDENTE GRAVE,VIT�RIA,ES,NaN,2017-02-21,11:47:00,12,N�O

In [22]:
# ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               S�O PAULO                   11
326         RIO DE JANEIRO                   19
530              S�O PAULO                   11
727               IT�POLIS                   11
872                 RECIFE                   23
884   S�O JOS� DOS PINHAIS                   11
1062            UBERL�NDIA                   20
1972              BRAS�LIA                   11
2795                SANTOS                   13
3930               VIT�RIA                   12

In [23]:
# ocorrências com mais de 10 recomendações
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 | filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
8,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2,N�O
9,39711,INCIDENTE GRAVE,PAR� DE MINAS,MG,NaN,2010-01-10,20:00:00,0,N�O
29,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2,SIM
35,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5740,79754,INCIDENTE GRAVE,NOVA MARING�,MT,NaN,2020-12-28,13:00:00,0,SIM
5743,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0,SIM
5745,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0,SIM
5747,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,NaN,2020-12-30,18:30:00,0,N�O
5749,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0,N�O

In [24]:
# ocorrencia cuja classificação = INCIDENTE GRAVE ou INCIDENTE, e o estado == SP
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE']) 
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 & filtro2]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
16,39809,INCIDENTE,S�O PAULO,SP,NaN,2010-01-15,15:00:00,0,N�O
18,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0,N�O
26,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0,N�O
27,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0,N�O
33,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5703,79739,INCIDENTE GRAVE,S�O PAULO,SP,SBSP,2020-12-03,14:42:00,0,N�O
5704,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0,N�O
5714,79718,INCIDENTE GRAVE,S�O PAULO,SP,SBMT,2020-12-11,13:50:00,0,SIM
5741,79800,INCIDENTE,S�O PAULO,SP,SBMT,2020-12-28,10:15:00,0,N�O
5746,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,N�O

In [25]:
# Ocorrência cuja cidade comece com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
6,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0,SIM
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
8,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
20,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5660,79649,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0,N�O
5662,79652,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0,N�O
5679,79683,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0,N�O
5695,79692,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0,SIM
5746,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,N�O

In [26]:
# Ocorrência cuja cidade termina com a letra A
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
12,40414,INCIDENTE,BRAS�LIA,DF,SBBR,2010-01-10,03:00:00,0,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
25,39772,INCIDENTE,UBERL�NDIA,MG,NaN,2010-01-20,18:58:00,0,N�O
26,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5737,79787,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0,N�O
5738,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0,N�O
5742,79824,ACIDENTE,RIO PARANA�BA,MG,SNRP,2020-12-28,17:00:00,0,N�O
5743,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0,SIM
5749,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0,N�O

In [27]:
# Ocorrência cujo nome da cidade termina com "MA"
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
408,43062,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1,N�O
688,44198,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0,N�O
1035,51785,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0,N�O
1377,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0,N�O
1401,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0,N�O
2099,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4,N�O
2102,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0,SIM
2655,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0,N�O
2855,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1,N�O
2966,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0,N�O
2997,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0,N�O
3040,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0,N�O
3092,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,N�O
3157,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0,N�O
3171,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2,SIM
3189,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0,N�O
3682,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1,N�O
3725,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0,N�O
3881,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0,N�O
4228,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1,SIM
4310,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0,N�O
4573,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0,N�O
4985,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0,N�O
5069,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0,N�O
5079,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0,N�O
5404,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0,N�O
5439,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0,N�O
5473,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0,N�O

In [28]:
# Ocorrência cujo nome da cidade termina com "MA"
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
408,43062,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1,N�O
688,44198,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0,N�O
1035,51785,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0,N�O
1377,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0,N�O
1401,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0,N�O
2099,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4,N�O
2102,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0,SIM
2655,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0,N�O
2855,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1,N�O
2966,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0,N�O
2997,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0,N�O
3040,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0,N�O
3092,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,N�O
3157,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0,N�O
3171,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2,SIM
3189,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0,N�O
3682,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1,N�O
3725,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0,N�O
3881,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0,N�O
4228,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1,SIM
4310,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0,N�O
4573,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0,N�O
4985,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0,N�O
5069,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0,N�O
5079,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0,N�O
5404,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0,N�O
5439,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0,N�O
5473,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0,N�O

In [29]:
# Ocorrência cuja cidade contém (em qualquer parte do conteúdo) os caracteres "MA"
filtro = df.ocorrencia_cidade.str.contains('MA|AL')
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
5,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0,N�O
7,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,N�O
13,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2,N�O
15,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0,N�O
17,39810,INCIDENTE,SALVADOR,BA,NaN,2010-01-15,18:23:00,0,N�O
...,...,...,...,...,...,...,...,...,...
5737,79787,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0,N�O
5738,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0,N�O
5740,79754,INCIDENTE GRAVE,NOVA MARING�,MT,NaN,2020-12-28,13:00:00,0,SIM
5744,79755,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0,N�O
5745,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0,SIM

In [30]:
# Ocorrência cuja do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
2996,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3,N�O
2997,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0,N�O
2998,53073,INCIDENTE,TEF�,AM,SBTF,2015-01-02,16:28:00,0,N�O
2999,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0,N�O
3000,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6,N�O
...,...,...,...,...,...,...,...,...,...
3462,60632,INCIDENTE GRAVE,ITABER�,SP,NaN,2015-12-24,14:00:00,0,N�O
3463,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0,N�O
3464,60642,INCIDENTE,S�O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0,N�O
3465,60631,ACIDENTE,MA�AMBAR�,RS,NaN,2015-12-28,19:00:00,2,N�O
3466,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0,SIM

In [31]:
# Ocorrência cuja do ano de 2015 e mês 12
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
df.loc[filtro1 & filtro2]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
3428,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0,N�O
3429,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0,N�O
3430,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0,N�O
3431,53636,INCIDENTE,JUNDIA�,SP,SBJD,2015-12-02,17:42:00,0,N�O
3432,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,N�O
3433,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,N�O
3434,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,N�O
3435,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,SIM
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O
3438,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,N�O
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O
3440,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0,N�O
3441,60604,INCIDENTE,GOI�NIA,GO,SBGO,2015-12-12,14:34:00,0,N�O
3442,60611,INCIDENTE,S�O PAULO,SP,SBSP,2015-12-12,15:30:00,0,N�O
3443,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0,N�O
3444,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0,N�O
3445,53630,INCIDENTE,MAR�LIA,SP,SBML,2015-12-13,13:50:00,0,N�O
3446,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0,N�O
3447,60612,ACIDENTE,BENTO GON�ALVES,RS,SSBG,2015-12-13,20:30:00,0,N�O
3448,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3,N�O
3449,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0,N�O
3450,60609,INCIDENTE GRAVE,ARAGUA�NA,TO,SWGN,2015-12-15,13:00:00,0,N�O
3451,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0,N�O
3452,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4,N�O
3453,60645,ACIDENTE,SERT�OZINHO,SP,NaN,2015-12-15,13:00:00,0,N�O
3454,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0,N�O
3455,60625,ACIDENTE,IT�POLIS,SP,SDIO,2015-12-17,21:30:00,1,SIM
3456,60605,INCIDENTE,UBERL�NDIA,MG,SBUL,2015-12-18,10:25:00,0,N�O
3457,60610,INCIDENTE,JUNDIA�,SP,SBJD,2015-12-18,18:45:00,0,N�O
3458,60602,INCIDENTE,RIBEIR�O PRETO,SP,SBRP,2015-12-22,06:27:00,0,N�O
3459,60615,INCIDENTE,S�O PAULO,SP,SBMT,2015-12-22,13:07:00,0,N�O
3460,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0,N�O
3461,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0,N�O
3462,60632,INCIDENTE GRAVE,ITABER�,SP,NaN,2015-12-24,14:00:00,0,N�O
3463,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0,N�O
3464,60642,INCIDENTE,S�O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0,N�O
3465,60631,ACIDENTE,MA�AMBAR�,RS,NaN,2015-12-28,19:00:00,2,N�O
3466,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0,SIM

In [32]:
# Ocorrência cuja do ano de 2015 e mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
3428,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0,N�O
3429,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0,N�O
3430,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0,N�O
3431,53636,INCIDENTE,JUNDIA�,SP,SBJD,2015-12-02,17:42:00,0,N�O
3432,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,N�O
3433,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,N�O
3434,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,N�O
3435,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,SIM
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O
3438,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,N�O
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O
3440,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0,N�O
3441,60604,INCIDENTE,GOI�NIA,GO,SBGO,2015-12-12,14:34:00,0,N�O
3442,60611,INCIDENTE,S�O PAULO,SP,SBSP,2015-12-12,15:30:00,0,N�O
3443,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0,N�O
3444,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0,N�O
3445,53630,INCIDENTE,MAR�LIA,SP,SBML,2015-12-13,13:50:00,0,N�O
3446,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0,N�O
3447,60612,ACIDENTE,BENTO GON�ALVES,RS,SSBG,2015-12-13,20:30:00,0,N�O
3448,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3,N�O
3449,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0,N�O
3450,60609,INCIDENTE GRAVE,ARAGUA�NA,TO,SWGN,2015-12-15,13:00:00,0,N�O
3451,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0,N�O
3452,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4,N�O
3453,60645,ACIDENTE,SERT�OZINHO,SP,NaN,2015-12-15,13:00:00,0,N�O
3454,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0,N�O
3455,60625,ACIDENTE,IT�POLIS,SP,SDIO,2015-12-17,21:30:00,1,SIM
3456,60605,INCIDENTE,UBERL�NDIA,MG,SBUL,2015-12-18,10:25:00,0,N�O
3457,60610,INCIDENTE,JUNDIA�,SP,SBJD,2015-12-18,18:45:00,0,N�O
3458,60602,INCIDENTE,RIBEIR�O PRETO,SP,SBRP,2015-12-22,06:27:00,0,N�O
3459,60615,INCIDENTE,S�O PAULO,SP,SBMT,2015-12-22,13:07:00,0,N�O
3460,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0,N�O
3461,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0,N�O
3462,60632,INCIDENTE GRAVE,ITABER�,SP,NaN,2015-12-24,14:00:00,0,N�O
3463,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0,N�O
3464,60642,INCIDENTE,S�O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0,N�O
3465,60631,ACIDENTE,MA�AMBAR�,RS,NaN,2015-12-28,19:00:00,2,N�O
3466,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0,SIM

In [33]:
# Ocorrência cuja do ano de 2015, mês 12 e dia 8
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = df.ocorrencia_dia.dt.day == 8
df.loc[filtro1 & filtro2 & filtro3 ]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O
3438,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,N�O
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O

In [34]:
# Ocorrência cuja do ano de 2015, mês 12 e dias 3 a 8
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
filtro3 = (df.ocorrencia_dia.dt.day > 2) & (df.ocorrencia_dia.dt.day < 9)
df.loc[filtro1 & filtro2 & filtro3 ]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista
3432,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,N�O
3433,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,N�O
3434,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,N�O
3435,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,SIM
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O
3438,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,N�O
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O

In [35]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [36]:
df.head()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,N�O,2010-01-03 12:00:00
1,40349,INCIDENTE,BEL�M,PA,SBBE,2010-01-03,11:05:00,0,N�O,2010-01-03 11:05:00
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,N�O,2010-01-03 03:00:00
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,N�O,2010-01-04 17:30:00
4,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,N�O,2010-01-05 19:25:00

In [37]:
df.dtypes

codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_saida_pista              object
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [38]:
# Ocorrência cuja do ano de 2015, mês 12 e dias 3 a 8
filtro1 = df.ocorrencia_dia_hora.dt.year == 2015
filtro2 = df.ocorrencia_dia_hora.dt.month == 12
filtro3 = (df.ocorrencia_dia_hora.dt.day > 2) & (df.ocorrencia_dia.dt.day < 9)
df.loc[filtro1 & filtro2 & filtro3 ]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
3432,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,N�O,2015-12-03 10:50:00
3433,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,N�O,2015-12-03 16:47:00
3434,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,N�O,2015-12-06 13:10:00
3435,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,SIM,2015-12-06 15:00:00
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O,2015-12-08 14:30:00
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O,2015-12-08 10:20:00
3438,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,N�O,2015-12-08 16:19:00
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O,2015-12-08 13:00:00

In [39]:
# Ocorrência cuja do ano de 2015, mês 12 e dias 3 a 8
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00' 
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
3433,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,N�O,2015-12-03 16:47:00
3434,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,N�O,2015-12-06 13:10:00
3435,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,SIM,2015-12-06 15:00:00
3436,53628,ACIDENTE,AGUA�,SP,NaN,2015-12-08,14:30:00,1,N�O,2015-12-08 14:30:00
3437,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,N�O,2015-12-08 10:20:00
3439,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,N�O,2015-12-08 13:00:00

In [40]:
# Ocorrência cuja do ano de 2015 e mês 3
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
3086,53183,ACIDENTE,AMAPOR�,PR,NaN,2015-03-02,23:00:00,0,N�O,2015-03-02 23:00:00
3087,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,N�O,2015-03-04 13:30:00
3088,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,N�O,2015-03-05 13:50:00
3089,53112,ACIDENTE,MOGI GUA�U,SP,NaN,2015-03-06,21:00:00,0,N�O,2015-03-06 21:00:00
3090,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,N�O,2015-03-10 11:30:00
3091,53167,INCIDENTE,MARAB�,PA,SBMA,2015-03-10,17:33:00,0,N�O,2015-03-10 17:33:00
3092,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,N�O,2015-03-10 21:35:00
3093,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,N�O,2015-03-11 23:25:00
3094,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,N�O,2015-03-12 12:40:00
3095,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,N�O,2015-03-13 15:45:00
3096,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,N�O,2015-03-13 14:40:00
3097,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,N�O,2015-03-13 11:30:00
3098,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0,N�O,2015-03-14 07:20:00
3099,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,N�O,2015-03-14 18:00:00
3100,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,N�O,2015-03-15 18:30:00
3101,53151,INCIDENTE GRAVE,MAU�S,AM,SWMW,2015-03-16,18:07:00,1,SIM,2015-03-16 18:07:00
3102,53168,INCIDENTE,PAR� DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,N�O,2015-03-16 21:05:00
3103,53169,INCIDENTE,BEL�M,PA,SBBE,2015-03-19,03:25:00,0,N�O,2015-03-19 03:25:00
3104,53165,INCIDENTE GRAVE,S�O DESID�RIO,BA,NaN,2015-03-20,14:35:00,0,N�O,2015-03-20 14:35:00
3105,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,N�O,2015-03-20 21:00:00
3106,53184,ACIDENTE,PORTO UNI�O,SC,NaN,2015-03-22,13:44:00,0,N�O,2015-03-22 13:44:00
3107,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,N�O,2015-03-23 17:15:00
3108,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,N�O,2015-03-23 20:40:00
3109,53166,INCIDENTE GRAVE,RIACH�O DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,N�O,2015-03-24 14:45:00
3110,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,N�O,2015-03-24 17:57:00
3111,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,N�O,2015-03-24 23:01:00
3112,53412,INCIDENTE GRAVE,MACA�,RJ,NaN,2015-03-24,16:35:00,0,N�O,2015-03-24 16:35:00
3113,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,SIM,2015-03-26 20:30:00
3114,53186,INCIDENTE,BRAS�LIA,DF,NaN,2015-03-27,14:55:00,0,N�O,2015-03-27 14:55:00
3115,53179,ACIDENTE,CAIAP�NIA,GO,NaN,2015-03-28,10:30:00,0,N�O,2015-03-28 10:30:00
3116,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,N�O,2015-03-28 18:52:00
3117,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,N�O,2015-03-28 16:26:00
3118,53212,INCIDENTE,JUNDIA�,SP,SBJD,2015-03-28,17:32:00,0,N�O,2015-03-28 17:32:00
3119,53213,INCIDENTE,JUNDIA�,SP,SBJD,2015-03-28,15:51:00,0,N�O,2015-03-28 15:51:00
3120,53181,ACIDENTE,COL�DER,MT,NaN,2015-03-29,20:17:00,0,N�O,2015-03-29 20:17:00
3121,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,N�O,2015-03-29 18:36:00
3122,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,N�O,2015-03-30 19:40:00

In [41]:
df201503.count()

codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_saida_pista      37
ocorrencia_dia_hora         37
dtype: int64

In [42]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia2.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia2, dtype: int64

In [43]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [44]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [45]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [46]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [47]:
# Verificar sudeste em 2010
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP', 'MG', 'ES', 'RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,N�O,2010-01-03 12:00:00
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,N�O,2010-01-03 03:00:00
9,39711,INCIDENTE GRAVE,PAR� DE MINAS,MG,NaN,2010-01-10,20:00:00,0,N�O,2010-01-10 20:00:00
11,40069,ACIDENTE,S�O PAULO,SP,SBMT,2010-01-10,14:50:00,8,N�O,2010-01-10 14:50:00
16,39809,INCIDENTE,S�O PAULO,SP,NaN,2010-01-15,15:00:00,0,N�O,2010-01-15 15:00:00
...,...,...,...,...,...,...,...,...,...,...
541,43722,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0,N�O,2010-12-23 11:00:00
544,43548,INCIDENTE,S�O PAULO,SP,SBSP,2010-12-26,22:10:00,0,N�O,2010-12-26 22:10:00
548,43724,ACIDENTE,COSM�POLIS,SP,NaN,2010-12-29,12:00:00,0,N�O,2010-12-29 12:00:00
550,43730,INCIDENTE,VIT�RIA,ES,NaN,2010-12-30,18:10:00,0,N�O,2010-12-30 18:10:00
551,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0,N�O,2010-12-30 14:28:00

In [48]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          170
INCIDENTE GRAVE     18
dtype: int64

In [49]:
dfsudeste2010.count()

codigo_ocorrencia2          228
ocorrencia_classificacao    228
ocorrencia_cidade           228
ocorrencia_uf               228
ocorrencia_aerodromo        127
ocorrencia_dia              228
ocorrencia_hora             228
total_recomendacoes         228
ocorrencia_saida_pista      228
ocorrencia_dia_hora         228
dtype: int64

In [50]:
dfsudeste2010.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             INCIDENTE                    5
MG             ACIDENTE                     7
               INCIDENTE                   39
               INCIDENTE GRAVE              5
RJ             ACIDENTE                     9
               INCIDENTE                   52
               INCIDENTE GRAVE              4
SP             ACIDENTE                    24
               INCIDENTE                   74
               INCIDENTE GRAVE              9
dtype: int64

In [51]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO           47
S�O PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACA�                    12
CONFINS                   7
UBERL�NDIA                5
JUIZ DE FORA              4
VIT�RIA                   4
MAR�LIA                   3
S�O JOS� DOS CAMPOS       3
S�O JOS� DO RIO PRETO     3
SOROCABA                  2
ITANHA�M                  2
RIBEIR�O PRETO            2
IPATINGA                  2
PO�OS DE CALDAS           2
DIVIN�POLIS               2
BAURU                     2
JUNDIA�                   2
ARARAQUARA                2
CAMPOS DOS GOYTACAZES     2
AREALVA                   2
MONTES CLAROS             2
UBERABA                   2
POUSO ALEGRE              1
PIRACICABA                1
PIRASSUNUNGA              1
ARRAIAL DO CABO           1
RESENDE                   1
PEN�POLIS                 1
SANTOS                    1
SERRA NEGRA               1
S�O BERNARDO DO CAMPO     1
TIM�TEO                   1
ARA�ATUBA                 1
PIACATU                   1
BOM JESUS DO AMPARO       1
PAR� DE MINAS             1
OL�MPIA                   1
BRAGAN�A PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSM�POLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPER�                     1
IT�POLIS                  1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
NOVO HORIZONTE            1
AMERICANA                 1
dtype: int64

In [52]:
filtro1 = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2 = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
119,40190,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3,N�O,2010-04-06 02:35:00
274,41750,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3,N�O,2010-07-12 19:53:00
326,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19,SIM,2010-08-12 12:26:00

In [53]:
filtro1 = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro1].total_recomendacoes.sum()

25

In [54]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0
ARARAQUARA                0
ARA�ATUBA                 0
AREALVA                   0
ARRAIAL DO CABO           0
BAURU                     0
BEBEDOURO                 0
BELO HORIZONTE            2
BOCAINA                   0
BOITUVA                   1
BOM JESUS DO AMPARO       0
BOM JESUS DO GALHO        1
BRAGAN�A PAULISTA         9
BROTAS                    0
CAJOBI                    0
CAMANDUCAIA               9
CAMPINAS                  0
CAMPOS DOS GOYTACAZES     0
CASIMIRO DE ABREU         0
CONFINS                   0
COROMANDEL                0
COSM�POLIS                0
DIAMANTINA                0
DIVIN�POLIS               0
GUARULHOS                 0
IPATINGA                  0
IPER�                     3
ITANHA�M                  1
IT�POLIS                  0
JUIZ DE FORA              0
JUNDIA�                   7
LINHARES                  0
MACA�                     0
MANGARATIBA               0
MAR�LIA                   0
MONTES CLAROS             0
NOVO HORIZONTE            3
OL�MPIA                   0
PAR� DE MINAS             0
PEN�POLIS                 0
PIACATU                   0
PIRACICABA                0
PIRASSUNUNGA              0
POUSO ALEGRE              0
PO�OS DE CALDAS           0
RESENDE                   8
RIBEIR�O PRETO            0
RIO DE JANEIRO           25
SANTOS                    0
SERRA NEGRA               0
SOROCABA                  0
S�O BERNARDO DO CAMPO     2
S�O JOS� DO RIO PRETO     0
S�O JOS� DOS CAMPOS       0
S�O PAULO                41
TIM�TEO                   3
UBERABA                   0
UBERL�NDIA                0
VIT�RIA                   0
Name: total_recomendacoes, dtype: int64

In [58]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBAE     0
SBAQ     0
SBBH     0
SBBP     9
SBBU     0
SBCF     0
SBGL     3
SBGR     0
SBIP     0
SBJD     7
SBJR     3
SBKP     0
SBME     0
SBMK     0
SBML     0
SBMT    27
SBPC     0
SBPR     1
SBRJ    19
SBRP     0
SBSJ     0
SBSP     0
SBSR     0
SBUL     0
SBUR     0
SBVT     0
SDAM     0
SDOI     1
SDPW     0
SDPY     0
SNDT     0
SNDV     0
SNXT     0
NaN     45
Name: total_recomendacoes, dtype: int64

In [61]:
dfsudeste2010.groupby(['ocorrencia_cidade'], dropna=False).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0
ARARAQUARA                0
ARA�ATUBA                 0
AREALVA                   0
ARRAIAL DO CABO           0
BAURU                     0
BEBEDOURO                 0
BELO HORIZONTE            2
BOCAINA                   0
BOITUVA                   1
BOM JESUS DO AMPARO       0
BOM JESUS DO GALHO        1
BRAGAN�A PAULISTA         9
BROTAS                    0
CAJOBI                    0
CAMANDUCAIA               9
CAMPINAS                  0
CAMPOS DOS GOYTACAZES     0
CASIMIRO DE ABREU         0
CONFINS                   0
COROMANDEL                0
COSM�POLIS                0
DIAMANTINA                0
DIVIN�POLIS               0
GUARULHOS                 0
IPATINGA                  0
IPER�                     3
ITANHA�M                  1
IT�POLIS                  0
JUIZ DE FORA              0
JUNDIA�                   7
LINHARES                  0
MACA�                     0
MANGARATIBA               0
MAR�LIA                   0
MONTES CLAROS             0
NOVO HORIZONTE            3
OL�MPIA                   0
PAR� DE MINAS             0
PEN�POLIS                 0
PIACATU                   0
PIRACICABA                0
PIRASSUNUNGA              0
POUSO ALEGRE              0
PO�OS DE CALDAS           0
RESENDE                   8
RIBEIR�O PRETO            0
RIO DE JANEIRO           25
SANTOS                    0
SERRA NEGRA               0
SOROCABA                  0
S�O BERNARDO DO CAMPO     2
S�O JOS� DO RIO PRETO     0
S�O JOS� DOS CAMPOS       0
S�O PAULO                41
TIM�TEO                   3
UBERABA                   0
UBERL�NDIA                0
VIT�RIA                   0
Name: total_recomendacoes, dtype: int64

In [63]:
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade'], dropna=False).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BOITUVA                   1
BOM JESUS DO GALHO        1
ITANHA�M                  1
BELO HORIZONTE            2
S�O BERNARDO DO CAMPO     2
IPER�                     3
NOVO HORIZONTE            3
TIM�TEO                   3
JUNDIA�                   7
RESENDE                   8
BRAGAN�A PAULISTA         9
CAMANDUCAIA               9
RIO DE JANEIRO           25
S�O PAULO                41
Name: total_recomendacoes, dtype: int64

In [65]:
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2010.ocorrencia_dia.dt.month], dropna=False).total_recomendacoes.sum()

ocorrencia_cidade      ocorrencia_dia
BELO HORIZONTE         2                  1
                       3                  1
BOITUVA                7                  1
BOM JESUS DO GALHO     12                 1
BRAGAN�A PAULISTA      11                 9
CAMANDUCAIA            7                  9
IPER�                  1                  3
ITANHA�M               9                  1
JUNDIA�                5                  5
                       6                  2
NOVO HORIZONTE         7                  3
RESENDE                4                  8
RIO DE JANEIRO         4                  3
                       7                  3
                       8                 19
S�O BERNARDO DO CAMPO  1                  2
S�O PAULO              1                  8
                       2                 14
                       6                  2
                       11                 6
                       12                11
TIM�TEO                2                  3
Name: total_recomendacoes, dtype: int64

In [68]:
filtro1 = dfsudeste2010.total_recomendacoes > 0
filtro2 = dfsudeste2010.ocorrencia_cidade == 'S�O PAULO'
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_saida_pista,ocorrencia_dia_hora
11,40069,ACIDENTE,S�O PAULO,SP,SBMT,2010-01-10,14:50:00,8,N�O,2010-01-10 14:50:00
58,39275,ACIDENTE,S�O PAULO,SP,NaN,2010-02-10,09:03:00,3,N�O,2010-02-10 09:03:00
63,39992,ACIDENTE,S�O PAULO,SP,SBMT,2010-02-17,20:07:00,11,SIM,2010-02-17 20:07:00
219,41411,INCIDENTE GRAVE,S�O PAULO,SP,SBMT,2010-06-08,19:30:00,2,SIM,2010-06-08 19:30:00
469,43450,ACIDENTE,S�O PAULO,SP,SBMT,2010-11-04,10:55:00,6,N�O,2010-11-04 10:55:00
530,43471,ACIDENTE,S�O PAULO,SP,NaN,2010-12-14,20:15:00,11,N�O,2010-12-14 20:15:00